# Data

The final dataset constructed for the analysis done in this project is a combination of the usage and schedule raw data files, described in the next section. It has 9 columns, five of which are independent variables. The unit of interest is a station, so each row in the final table describes a station. The dataset contains one dependent variable, one category variable, and two descriptors about each station. Each station stop is described by its ID in the TriMet system as well as the name of the station, which is typically related to its location in some way. Transit centers and street intersections are common name formats. Each station has associated with it a combined usage number across all the routes that stop there, including both onboardings and disembarkings. This usage total acts as our dependent variable. Independent variables engineered from the schedule data (see *Feature Engineering*) are as follows: number of routes that stop at the station, the earliest and latest arrivals at that station, the number of unique vehicles that arrive at the station over the course of the day, and the average number of minutes between arrivals. These values are calculated for both weekdays and weekend days, since the schedules can vary between weekdays and the weekend. Some routes do not run on the weekends, and thus only have weekday information given. Weekday information has a Boolean day value of 0, and weekend information has a value of 1. 