# Conclusions

Over the course of this project, we went through the data collection and engineering process as well as modeling usage using statistical and machine learning-based regressions. Two types of data were collected from the TriMet website: usage information by station for Spring 2025, and schedule information for each station. These values were uploaded into a database, as well as transformed into a number of features for use in predicting the usage value of a station. 

We experimented with multiple Poisson regression models, but ultimately weren’t able to generate accurate predictions. Plotting usage against predicted usage shows a scatterplot of points randomly spread on either side of the y=x diagonal line. Additionally, the summary of the model shows that each variable has negligible effects on usage. It’s possible that a different statistical model should be used, but more likely that the features we created are simply not good predictors of usage.

A number of random forest models were used to predict usage, at a number of scales. Usage was predicted over the full dataset, as well as for several categories: MAX stations, low-usage bus stations, medium-usage bus stations, and high-usage bus stations. Of these models, the one trained on the full dataset had the highest metrics, with an R^2 value during training of [FINAL VALUE]. The models trained on smaller proportions of the dataset performed worse than this full model, while the low-usage bus station model was comparable, due to its status as containing the majority of the data in the dataset. However, with a test RMSE value of [80-ISH, GET FINAL VALUE], even the highest-performing model does not make a good predictor for a dataset with a mean of 30. 

## Future Work 

In some ways, the fact that schedule information alone is not particularly predictive of usage is not a surprising discovery. Future work done on this problem would benefit highly from the inclusion of location data for each station stop, which was unfortunately not easily available within the timeframe of this project. Potential inclusions beyond merely location data could be information that provides context to the neighborhood the station is in: how many people live within a certain radius, is this station part of a transit center or not, is there parking available nearby? And other possible questions that would allow for a holistic understanding of the station, rather than merely focusing on the schedule as set up by TriMet. 

[SUGGESTED GRAPH: TOP AND BOTTOM 5 USAGE STOPS BY LOCATION. ADD PORTLAND MAP WITH POPULATION DISTRICTS?]

## In Conclusion

All in all, this was a high-level analysis of TriMet usage data. We provide a database of usage data by station for Spring 2025, which also includes schedule information for each stop. This data was used to engineer a handful of features that were used to predict usage numbers, but the resulting predictions were not particularly high-scoring on any of the accuracy metrics investigated. Future work that provides location context to stations is likely to improve our ability to predict TriMet station usage. 
